variables:
  IMAGE_NAME: schmts/current-time
  IMAGE_TAG: latest

stages:
  - build 
  - package&push
  - deploy_to_dev
  - deploy_to_prod

build_python:
  stage: build
  image: python:3.8-slim-buster
  script:
    - pip install -r requirements.txt

docker_image_hub:
  stage: package&push
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u schmts -p $DOCKER_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy_1:
  stage: deploy_to_dev
  image: ruby:latest
  rules:
    - if: '$CI_COMMIT_REF_NAME == "dev"'
      when: always
      allow_failure: true
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$RUNNER_PRIVATE_KEY" | tr -d '\r')
    - ssh generic@192.168.0.103 "kubectl apply -f ~/kontrolna/current-time-deployment-service.yaml && kubectl rollout restart deployment/curr-time -n dev"

deploy_2:
  stage: deploy_to_prod
  image: ruby:latest
  rules:
    - if: '$CI_COMMIT_REF_NAME == "prod"'
      when: always
      allow_failure: true
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$RUNNER_PRIVATE_KEY" | tr -d '\r')
    - ssh generic@192.168.0.103 "kubectl apply -f ~/kontrolna/current-time-deployment-service-prod.yaml && kubectl rollout restart deployment/curr-time -n prod"
