apiVersion: apps/v1
kind: Deployment
metadata:
  name: curr-time
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curr-time
  template:
    metadata:
      labels:
        app: curr-time
    spec:
      containers:
      - name: curr-time
        image: schmts/current-time:latest
---
apiVersion: v1
kind: Service
metadata:
  name: curr-time
  namespace: dev
spec:
  type: NodePort
  selector:
    app: curr-time
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001
