
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: service-accountR
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "nodes", "deployments", "services", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: account-serviceRB
  namespace: dev
subjects:
  - kind: User
    name: servisni-racun
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: service-accountR
  apiGroup: rbac.authorization.k8s.io
